repos:
- repo: https://github.com/psf/black
  rev: 26.5.1
  hooks:
  - id: black
    language_version: python3.11

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.1
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: requirements-txt-fixer

- repo: https://github.com/pycqa/isort
  rev: 8.0.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
